var searchData=
[
  ['getalllibrarieswhereisbookfreeforuser',['GetAllLibrariesWhereIsBookFreeForUser',['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_library_entities.html#a9aa5fedbe4c2a5ab5f186cee08816695',1,'EasyLibraryApplication.WPF.Model.LibraryEntities.GetAllLibrariesWhereIsBookFreeForUser(string bookISBN, Nullable&lt; int &gt; userID)'],['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_library_entities.html#acbdab1601ec88b793113cfe81f7c1584',1,'EasyLibraryApplication.WPF.Model.LibraryEntities.GetAllLibrariesWhereIsBookFreeForUser(string bookISBN, Nullable&lt; int &gt; userID, MergeOption mergeOption)']]],
  ['getalllibrarieswhereisbookfreeforuser_5fresult',['GetAllLibrariesWhereIsBookFreeForUser_Result',['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_get_all_libraries_where_is_book_free_for_user___result.html',1,'EasyLibraryApplication::WPF::Model']]],
  ['getalllibrarieswhereisbookfreeforuser_5fresult_2ecs',['GetAllLibrariesWhereIsBookFreeForUser_Result.cs',['../_get_all_libraries_where_is_book_free_for_user___result_8cs.html',1,'']]],
  ['getalllibrarysforuser',['GetAllLibrarysForUser',['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_library_entities.html#ad7f09de90250a4549e1e9a00fb8b5d20',1,'EasyLibraryApplication.WPF.Model.LibraryEntities.GetAllLibrarysForUser(Nullable&lt; int &gt; userId)'],['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_library_entities.html#a5d7dba8d4df0510125d3099544bdc446',1,'EasyLibraryApplication.WPF.Model.LibraryEntities.GetAllLibrarysForUser(Nullable&lt; int &gt; userId, MergeOption mergeOption)']]],
  ['getalllibrarysforuser_5fresult',['GetAllLibrarysForUser_Result',['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_get_all_librarys_for_user___result.html',1,'EasyLibraryApplication::WPF::Model']]],
  ['getalllibrarysforuser_5fresult_2ecs',['GetAllLibrarysForUser_Result.cs',['../_get_all_librarys_for_user___result_8cs.html',1,'']]],
  ['getalllibrarysforusernotregistered',['GetAllLibrarysForUserNotRegistered',['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_library_entities.html#aab81a8213f268a6145002a2b48f9e5f8',1,'EasyLibraryApplication.WPF.Model.LibraryEntities.GetAllLibrarysForUserNotRegistered(Nullable&lt; int &gt; userId)'],['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_library_entities.html#a916e19251929ee6cc10c7c16207963d9',1,'EasyLibraryApplication.WPF.Model.LibraryEntities.GetAllLibrarysForUserNotRegistered(Nullable&lt; int &gt; userId, MergeOption mergeOption)']]],
  ['getalllibrarysforusernotregistered_5fresult',['GetAllLibrarysForUserNotRegistered_Result',['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_get_all_librarys_for_user_not_registered___result.html',1,'EasyLibraryApplication::WPF::Model']]],
  ['getalllibrarysforusernotregistered_5fresult_2ecs',['GetAllLibrarysForUserNotRegistered_Result.cs',['../_get_all_librarys_for_user_not_registered___result_8cs.html',1,'']]],
  ['getallloansforuser',['GetAllLoansForUser',['../class_easy_library_application_1_1_w_p_f_1_1_model_1_1_library_entities.html#af44eeece49e0c500e1e4abdc85890391',1,'EasyLibraryApplication::WPF::Model::LibraryEntities']]],
  ['gethashstring',['GetHashString',['../class_password_hash_1_1_password.html#a87f41cd184f99c0d579e098e7edb8c77',1,'PasswordHash::Password']]],
  ['getqrcodebitmap',['GetQrCodeBitmap',['../class_qr_code_generator_1_1_qr_code.html#afcb7ea41edae80596a5ba5d857fa3e32',1,'QrCodeGenerator::QrCode']]]
];
