//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLibraryApplication.WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int LibraryId { get; set; }
        public int UserId { get; set; }
        public System.DateTime StartOfWork { get; set; }
        public Nullable<System.DateTime> EndOfWork { get; set; }
    
        public virtual Library Library { get; set; }
        public virtual User User { get; set; }
    }
}
