//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLibraryApplication.WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int UserId { get; set; }
        public int CopyId { get; set; }
        public System.DateTime LoanDate { get; set; }
        public Nullable<System.DateTime> EndLoanDate { get; set; }
        public Nullable<double> OverdueAmount { get; set; }
    
        public virtual Copy Copy { get; set; }
        public virtual User User { get; set; }
    }
}
